import re
from playwright.sync_api import Page, expect
import pytest

def test_create_contract(auth_page: Page):
    auth_page.goto("/Admin/Contract")

    auth_page.get_by_role("link", name=" Thêm mới").click()
    auth_page.get_by_role("textbox", name="Tiêu đề").click()
    auth_page.get_by_role("textbox", name="Tiêu đề").fill("HD san pham Sorimachi 1")
    auth_page.get_by_role("textbox", name="Số hợp đồng").click()
    auth_page.get_by_role("textbox", name="Số hợp đồng").fill("HD An 006")
    auth_page.get_by_label("Loại hợp đồng").select_option("0")
    auth_page.get_by_role("textbox", name="Ngày hợp đồng").click()
    auth_page.get_by_label("Month").nth(1).select_option("0")
    auth_page.get_by_label("Tháng 1 29,").nth(1).click()
    # auth_page.get_by_role("textbox", name="Ngày hợp đồng").fill("29/01/2026")
    auth_page.get_by_role("textbox", name="Ngày bắt đầu").click()
    auth_page.get_by_label("Tháng 2 2,").nth(2).click()
    # auth_page.get_by_role("textbox", name="Ngày bắt đầu").fill("02/02/2026")
    auth_page.get_by_role("textbox", name="Ngày kết thúc").click()
    auth_page.locator(".flatpickr-calendar.animate.open > .flatpickr-months > .flatpickr-next-month > svg").click()
    auth_page.locator(".flatpickr-calendar.animate.open > .flatpickr-months > .flatpickr-month > .flatpickr-current-month > .numInputWrapper > .arrowUp").click()
    auth_page.get_by_label("Tháng 3 10,").click()
    # auth_page.get_by_role("textbox", name="Ngày kết thúc").fill("10/03/2027")
    auth_page.get_by_label("Quy trình HĐ").select_option("5")
    auth_page.get_by_role("combobox", name="Mẫu hóa đơn").click()
    auth_page.get_by_role("combobox", name="Mẫu hóa đơn").fill("1C25TAZ")
    auth_page.get_by_title("Thêm mới").click()
    auth_page.locator("#ContractItems_0__TotalAmount").click()
    auth_page.locator("#ContractItems_0__TotalAmount").fill("2,000,000")
    auth_page.get_by_title("Thêm mới").click()
    auth_page.locator("#ContractItems_1__ServiceOption").select_option("2")
    auth_page.locator("#ContractItems_1__TotalAmount").click()
    auth_page.locator("#ContractItems_1__TotalAmount").fill("3,000,000")
    auth_page.get_by_role("textbox", name="Tên đơn vị bên B").click()
    auth_page.get_by_role("textbox", name="Tên đơn vị bên B").fill("Hop Tac Xa Rau Ru Xanh")
    auth_page.get_by_role("textbox", name="Mã số thuế bên B").click()
    auth_page.get_by_role("textbox", name="Mã số thuế bên B").fill("05676554688")
    auth_page.get_by_role("textbox", name="Người đại diện bên B", exact=True).click()
    auth_page.get_by_role("textbox", name="Người đại diện bên B", exact=True).fill("Nguyen Van An")
    auth_page.get_by_role("textbox", name="Chức vụ người đại diện bên B").click()
    auth_page.get_by_role("textbox", name="Chức vụ người đại diện bên B").fill("Giam Doc")
    auth_page.get_by_role("textbox", name="Số điện thoại bên B").click()
    auth_page.get_by_role("textbox", name="Số điện thoại bên B").fill("03333333333")
    auth_page.get_by_role("textbox", name="Email bên B").click()
    auth_page.get_by_role("textbox", name="Email bên B").fill("ngocan220301@gmail.com")
    auth_page.get_by_role("textbox", name="Địa chỉ bên B").click()
    auth_page.get_by_role("textbox", name="Địa chỉ bên B").fill("Bau Cat 8, phuong 14, Tan Binh")
    auth_page.get_by_role("button", name=" Lưu bản nháp").click()
    auth_page.get_by_role("textbox", name="Mã số thuế bên B").click()
    auth_page.get_by_role("textbox", name="Mã số thuế bên B").fill("0567655468")
    auth_page.get_by_role("button", name=" Lưu bản nháp").click()
    expect(auth_page).to_have_url(re.compile(r".*/Admin/Contract$"))

